[options]
addons_path =
    ../../17.0/odoo/addons,
    ../../17.0/enterprise,
    ./,
    ./account-analytic,
    ./account-financial-reporting,
    ./account-financial-tools,
    ./account-payment,
    ./account-reconcile,
    ./bank-payment,
    ./bank-statement-import,
    ./credit-control,
    ./edi-document,
    ./google-spreadsheet-import,
    ./l10n-edi-hr-expense,
    ./l10n-mx-avoid-reversal-entry,
    ./l10n-mx-check-printing,
    ./l10n-mx-edi-advance,
    ./l10n-mx-edi-hr-expense,
    ./l10n-mx-edi-product-refund-accounts,
    ./l10n-mx-edi-related-documents,
    ./l10n-mx-partner-blocklist,
    ./manufacture,
    ./mexico-document,
    ./mis-builder,
    ./odoo-cloc,
    ./product-attribute,
    ./purchase-workflow,
    ./real,
    ./reporting-engine,
    ./server-backend,
    ./server-tools,
    ./server-ux,
    ./stock-logistics-availability,
    ./stock-logistics-reporting,
    ./stock-logistics-request,
    ./stock-logistics-warehouse,
    ./stock-logistics-workflow,
    ./web
admin_passwd = 147852
data_dir = ~/.local/share/Odoo
limit_memory_hard = 0
limit_memory_soft = 2147483648
limit_request = 8192
limit_time_cpu = 600000
limit_time_real = 120000
